# 1. Server Configuration (Forces it to run on 8081)
server.port=8080

# 2. Render Database Configuration (Points to where we saved Don Divin's data)
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d8p972lckfvc73a4dne0-a.oregon-postgres.render.com:5432/mock_auca_db_7nua}
spring.datasource.username=${DB_USER:mock_auca_db_7nua_user}
spring.datasource.password=${DB_PASS:3NhpgYdjidiWNsOaWPoRU9LSwtT0UFGC}

# 3. JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect